version: '3.9'
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5051:5050'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - '8001:5000'
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  data: